language: java
jdk: oraclejdk7

before_install:
  # required libs for android build tools
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # for gradle output style
  - export TERM=dumb
  # newer version of gradle
  - wget http://services.gradle.org/distributions/gradle-1.10-bin.zip
  - unzip -qq gradle-1.10-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.10
  - export PATH=$GRADLE_HOME/bin:$PATH
  - chmod +x gradlew
  # newest Android SDK 23.0.1
  - wget http://dl.google.com/android/android-sdk_r23.0.1-linux.tgz
  - tar -zxf android-sdk_r23.0.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # newest Android NDK
  - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86.bin -O ndk.bin; fi
  - chmod a+x ndk.bin
  - ./ndk.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
  # manually set sdk.dir variable, according to local paths
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo yes | android update sdk -a -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-23,build-tools-23.0.1,extra-google-google_play_services,extra-google-m2repository --force --no-ui


install:
  - true

script:
  - ./gradlew cleanTest test -PdisablePreDex

env:
  matrix:
    - TEST_TYPE=android
  global:
    # $GITHUB_TOKEN
    - secure: "HlmG8M2DmBUSBh6KH1yVIe/8gR4iibg4WfcHq1x/xYQxGbvleq7NOo04V6eFHnl9cvZCu+PKH0841WLnGR7c4BBf47GVu/o16nXzggPumHKy++lDzxFPlJ1faMDfjg/5vjbAxRUe7D3y98hQSeGHH4tedc8LvTaFLVu7iiGqvjU="
    # $APPETIZE_TOKEN
    - secure: "egsvVSpszTzrNd6bN62DsVAzMiSZI/OHgdizfPryqvqWBf655ztE6XFQSEFNpuIAzSKDDF25ioT8iPfVsbC1iK6HDWHfmqYxML0L+OoU0gi+hV2oKUBFZDZ1fwSnFoWuBdNdMDpLlUxvJp6N1WyfNOB2dxuZUt8eTt48Hi3+Hpc="
    # $S3_TOKEN
    - secure: "lY8JZPA0A7zT7L5KF9BBg34XYWIeR/RJiEvE7l7oVr88KnEPtyd//79eHhhVKnUnav7zsk5QJwkcX0MxKTp/dp4G0Am+zOX+sfA8kQrJ+2/+FzFW7AEsW/kHByfaIEIly9DQvUFt4I4oMm8nQZysJLahDgNWglyI3RTuJp//hcY="

branches:
  only:
    - master
    - /^.*-stable$/
