name: Maestro E2E iOS
description: Runs E2E Tests on iOS using Maestro
inputs:
  app-path:
    required: true
    description: The path to the .app file
  app-id:
    required: true
    description: The id of the app to test
  jsengine:
    required: true
    description: The js engine we are using
  maestro-flow:
    required: true
    description: the folder that contains the maestro tests
runs:
  using: composite
  steps:
    - name: Installing Maestro
      shell: bash
      run: curl -Ls "https://get.maestro.mobile.dev" | bash
    - name: Installing Maestro dependencies
      shell: bash
      run: |
        brew tap facebook/fb
        brew install facebook/fb/idb-companion jq
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Run tests
      id: run-tests
      shell: bash
      run: sh ./.github/workflow-scripts/maestro/runTestsIOS.sh
    - name: Store video record
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e_ios_${{ inputs.app-id }}_report_${{ inputs.jsengine }}
        path: |
          video_record_1.mov
          video_record_2.mov
          video_record_3.mov
          report.xml
    - name: Store Logs
      if: failure() && steps.run-tests.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: maestro-logs-${{ inputs.app-id }}-${{ inputs.jsengine }}
        path: /tmp/MaestroLogs
