name: build-android
description: This action builds android
inputs:
  release-type:
    required: true
    description: The type of release we are building. It could be nightly, release or dry-run
runs:
  using: composite
  steps:
    - name: Setup git safe folders
      shell: bash
      run: git config --global --add safe.directory '*'
    - name: Setup node.js
      uses: ./.github/actions/setup-node
    - name: Install dependencies
      shell: bash
      run: yarn install --non-interactive
    - name: Set React Native Version
      shell: bash
      run: node ./scripts/releases/set-rn-artifacts-version.js --build-type ${{ inputs.release-type }}
    - name: Setup gradle
      uses: ./.github/actions/setup-gradle
      with:
        cache-read-only: "false"
    - name: Build and publish all the Android Artifacts to /tmp/maven-local
      shell: bash
      run: |
        # By default we only build ARM64 to save time/resources. For release/nightlies/prealpha, we override this value to build all archs.
        if [[ "${{ inputs.release-type }}" == "dry-run" ]]; then
          export ORG_GRADLE_PROJECT_reactNativeArchitectures="arm64-v8a"
        else
          export ORG_GRADLE_PROJECT_reactNativeArchitectures="armeabi-v7a,arm64-v8a,x86,x86_64"
        fi
        ./gradlew publishAllToMavenTempLocal build -PenableWarningsAsErrors=true
    - name: Upload Maven Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-local-build-android
        path: /tmp/maven-local
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: build-android-results
        compression-level: 1
        path: |
          packages/react-native-gradle-plugin/react-native-gradle-plugin/build/reports
          packages/react-native-gradle-plugin/settings-plugin/build/reports
          packages/react-native/ReactAndroid/build/reports
    - name: Upload RNTester APK - hermes-debug
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: rntester-hermes-debug
        path: packages/rn-tester/android/app/build/outputs/apk/hermes/debug/
        compression-level: 0
    - name: Upload RNTester APK - hermes-release
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: rntester-hermes-release
        path: packages/rn-tester/android/app/build/outputs/apk/hermes/release/
        compression-level: 0
    - name: Upload RNTester APK - jsc-debug
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: rntester-jsc-debug
        path: packages/rn-tester/android/app/build/outputs/apk/jsc/debug/
        compression-level: 0
    - name: Upload RNTester APK - jsc-release
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: rntester-jsc-release
        path: packages/rn-tester/android/app/build/outputs/apk/jsc/release/
        compression-level: 0
